language: cpp
compiler: gcc

matrix:
  include:
- os: linux
  compiler: x86_64-w64-mingw32-g++
  env: OPJ_CI_CC=x86_64-w64-mingw32-gcc OPJ_CI_CXX=x86_64-w64-mingw32-g++ OPJ_CI_ARCH=x86_64 OPJ_CI_BUILD_CONFIGURATION=Release
  dist: trusty
  addons:
     apt:
        packages:
           - gcc-mingw-w64-base
           - binutils-mingw-w64-x86-64
           - gcc-mingw-w64-x86-64
           - gcc-mingw-w64
           - g++-mingw-w64-x86-64
            
script:
- g++ -c -std=c++11 "BSM Simulator/BSIM.cpp"
- g++ -c -std=c++11 "Control Loop/CLoop.cpp"
